name: BUILD

on:
  push:
    branches:
      - my_develop
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint -- --no-fix

      - name: Run tests
        run: |
          npm run test:unit

      - name: Run circular references check
        run: |
          npm run circular-check -- --no-spinner

      - name: Build
        run: |
          npm run build

      - name: Upload fluidd.zip
        uses: actions/upload-artifact@v3
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

  publish-docker:
    name: Publish Docker Image
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download fluidd.zip
        uses: actions/download-artifact@v3
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

      - name: Prepare Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=vj-latest,enable=${{ github.ref == 'refs/heads/my_develop' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
